# Generated by Django 2.2 on 2022-05-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220429_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='contact',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
